# Import Libraries

In [42]:
import pandas as pd
import os

# File's Path

In [53]:
notebook_path = os.getcwd()
db_files_path = "D:\Documentos\Turbinas\Test_22ITIBarge5MWSimulations"

In [7]:
#print(notebook_path)
#print(db_files_path)

C:\Users\Victor Ramos Fuentes\Documents\Turbinas
D:\Documentos\Turbinas\Test_22ITIBarge5MWSimulations

In [54]:
fileJ1 = db_files_path + "\Test22Windrandompitchrandom.xlsx"
fileJ2 = db_files_path + "\Test22Windrandompitchrandom2.xlsx"

# Read File

In [55]:
df1 = pd.read_excel(fileJ1)
df2 = pd.read_excel(fileJ2)

# File's Analysis

## File's dimensions

In [56]:
print("File J1 -> " + "Number of rows: " + str(df1.shape[0]) + " Number of columns: " + str(df1.shape[1]))
print("File J2 -> " + "Number of rows: " + str(df2.shape[0]) + " Number of columns: " + str(df2.shape[1]))

File J1 -> Number of rows: 24001 Number of columns: 97
File J2 -> Number of rows: 4801 Number of columns: 97

## File's columns

In [57]:
df1.columns

Index(['Time', 'Wind1VelX', 'Wind1VelY', 'Wind1VelZ', 'BldPitch1', 'BldPitch2',
       'BldPitch3', 'Azimuth', 'RotSpeed', 'GenSpeed', 'NacYaw', 'OoPDefl1',
       'IPDefl1', 'TwstDefl1', 'OoPDefl2', 'IPDefl2', 'TwstDefl2', 'OoPDefl3',
       'IPDefl3', 'TwstDefl3', 'TwrClrnc1', 'TwrClrnc2', 'TwrClrnc3',
       'NcIMUTAxs', 'NcIMUTAys', 'NcIMUTAzs', 'TTDspFA', 'TTDspSS',
       'TTDspTwst', 'PtfmSurge', 'PtfmSway', 'PtfmHeave', 'PtfmRoll',
       'PtfmPitch', 'PtfmYaw', 'PtfmTAxt', 'PtfmTAyt', 'PtfmTAzt', 'RootFxc1',
       'RootFyc1', 'RootFzc1', 'RootMxc1', 'RootMyc1', 'RootMzc1', 'RootFxc2',
       'RootFyc2', 'RootFzc2', 'RootMxc2', 'RootMyc2', 'RootMzc2', 'RootFxc3',
       'RootFyc3', 'RootFzc3', 'RootMxc3', 'RootMyc3', 'RootMzc3', 'Spn1MLxb1',
       'Spn1MLyb1', 'Spn1MLzb1', 'Spn1MLxb2', 'Spn1MLyb2', 'Spn1MLzb2',
       'Spn1MLxb3', 'Spn1MLyb3', 'Spn1MLzb3', 'RotThrust', 'LSSGagFya',
       'LSSGagFza', 'RotTorq', 'LSSGagMya', 'LSSGagMza', 'YawBrFxp',
       'YawBrFyp', 'YawBrFzp', 'YawBrMxp', 'YawBrMyp', 'YawBrMzp', 'TwrBsFxt',
       'TwrBsFyt', 'TwrBsFzt', 'TwrBsMxt', 'TwrBsMyt', 'TwrBsMzt', 'TwHt1MLxt',
       'TwHt1MLyt', 'TwHt1MLzt', 'GenPwr', 'GenTq', 'Wave1Elev', 'T[1]',
       'T[2]', 'T[3]', 'T[4]', 'T[5]', 'T[6]', 'T[7]', 'T[8]'],
      dtype='object')

In [59]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24001 entries, 0 to 24000
Data columns (total 97 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Time       24001 non-null  float64
 1   Wind1VelX  24001 non-null  float64
 2   Wind1VelY  24001 non-null  float64
 3   Wind1VelZ  24001 non-null  float64
 4   BldPitch1  24001 non-null  float64
 5   BldPitch2  24001 non-null  float64
 6   BldPitch3  24001 non-null  float64
 7   Azimuth    24001 non-null  float64
 8   RotSpeed   24001 non-null  float64
 9   GenSpeed   24001 non-null  float64
 10  NacYaw     24001 non-null  float64
 11  OoPDefl1   24001 non-null  float64
 12  IPDefl1    24001 non-null  float64
 13  TwstDefl1  24001 non-null  int64
 14  OoPDefl2   24001 non-null  float64
 15  IPDefl2    24001 non-null  float64
 16  TwstDefl2  24001 non-null  int64
 17  OoPDefl3   24001 non-null  float64
 18  IPDefl3    24001 non-null  float64
 19  TwstDefl3  24001 non-null  int64
 20  TwrClrnc1  24001 non-null  float64
 21  TwrClrnc2  24001 non-null  float64
 22  TwrClrnc3  24001 non-null  float64
 23  NcIMUTAxs  24001 non-null  float64
 24  NcIMUTAys  24001 non-null  float64
 25  NcIMUTAzs  24001 non-null  float64
 26  TTDspFA    24001 non-null  float64
 27  TTDspSS    24001 non-null  float64
 28  TTDspTwst  24001 non-null  int64
 29  PtfmSurge  24001 non-null  float64
 30  PtfmSway   24001 non-null  float64
 31  PtfmHeave  24001 non-null  float64
 32  PtfmRoll   24001 non-null  float64
 33  PtfmPitch  24001 non-null  float64
 34  PtfmYaw    24001 non-null  float64
 35  PtfmTAxt   24001 non-null  float64
 36  PtfmTAyt   24001 non-null  float64
 37  PtfmTAzt   24001 non-null  float64
 38  RootFxc1   24001 non-null  float64
 39  RootFyc1   24001 non-null  float64
 40  RootFzc1   24001 non-null  float64
 41  RootMxc1   24001 non-null  float64
 42  RootMyc1   24001 non-null  float64
 43  RootMzc1   24001 non-null  float64
 44  RootFxc2   24001 non-null  float64
 45  RootFyc2   24001 non-null  float64
 46  RootFzc2   24001 non-null  float64
 47  RootMxc2   24001 non-null  float64
 48  RootMyc2   24001 non-null  float64
 49  RootMzc2   24001 non-null  float64
 50  RootFxc3   24001 non-null  float64
 51  RootFyc3   24001 non-null  float64
 52  RootFzc3   24001 non-null  float64
 53  RootMxc3   24001 non-null  float64
 54  RootMyc3   24001 non-null  float64
 55  RootMzc3   24001 non-null  float64
 56  Spn1MLxb1  24001 non-null  float64
 57  Spn1MLyb1  24001 non-null  float64
 58  Spn1MLzb1  24001 non-null  float64
 59  Spn1MLxb2  24001 non-null  float64
 60  Spn1MLyb2  24001 non-null  float64
 61  Spn1MLzb2  24001 non-null  float64
 62  Spn1MLxb3  24001 non-null  float64
 63  Spn1MLyb3  24001 non-null  float64
 64  Spn1MLzb3  24001 non-null  float64
 65  RotThrust  24001 non-null  float64
 66  LSSGagFya  24001 non-null  float64
 67  LSSGagFza  24001 non-null  float64
 68  RotTorq    24001 non-null  float64
 69  LSSGagMya  24001 non-null  float64
 70  LSSGagMza  24001 non-null  float64
 71  YawBrFxp   24001 non-null  float64
 72  YawBrFyp   24001 non-null  float64
 73  YawBrFzp   24001 non-null  float64
 74  YawBrMxp   24001 non-null  float64
 75  YawBrMyp   24001 non-null  float64
 76  YawBrMzp   24001 non-null  float64
 77  TwrBsFxt   24001 non-null  float64
 78  TwrBsFyt   24001 non-null  float64
 79  TwrBsFzt   24001 non-null  float64
 80  TwrBsMxt   24001 non-null  float64
 81  TwrBsMyt   24001 non-null  float64
 82  TwrBsMzt   24001 non-null  float64
 83  TwHt1MLxt  24001 non-null  float64
 84  TwHt1MLyt  24001 non-null  float64
 85  TwHt1MLzt  24001 non-null  float64
 86  GenPwr     24001 non-null  float64
 87  GenTq      24001 non-null  float64
 88  Wave1Elev  24001 non-null  int64
 89  T[1]       24001 non-null  float64
 90  T[2]       24001 non-null  float64
 91  T[3]       24001 non-null  float64
 92  T[4]       24001 non-null  float64
 93  T[5]       24001 non-null  float64
 94  T[6]       24001 non-null  float64
 95  T[7]       24001 non-null  float64
 96  T[8]       24001 non-null  float64
dtypes: float64(92), int64(5)
memory usage: 17.8 MB

In [58]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4801 entries, 0 to 4800
Data columns (total 97 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Time       4801 non-null   float64
 1   Wind1VelX  4801 non-null   float64
 2   Wind1VelY  4801 non-null   float64
 3   Wind1VelZ  4801 non-null   float64
 4   BldPitch1  4801 non-null   float64
 5   BldPitch2  4801 non-null   float64
 6   BldPitch3  4801 non-null   float64
 7   Azimuth    4801 non-null   float64
 8   RotSpeed   4801 non-null   float64
 9   GenSpeed   4801 non-null   float64
 10  NacYaw     4801 non-null   float64
 11  OoPDefl1   4801 non-null   float64
 12  IPDefl1    4801 non-null   float64
 13  TwstDefl1  4801 non-null   int64
 14  OoPDefl2   4801 non-null   float64
 15  IPDefl2    4801 non-null   float64
 16  TwstDefl2  4801 non-null   int64
 17  OoPDefl3   4801 non-null   float64
 18  IPDefl3    4801 non-null   float64
 19  TwstDefl3  4801 non-null   int64
 20  TwrClrnc1  4801 non-null   float64
 21  TwrClrnc2  4801 non-null   float64
 22  TwrClrnc3  4801 non-null   float64
 23  NcIMUTAxs  4801 non-null   float64
 24  NcIMUTAys  4801 non-null   float64
 25  NcIMUTAzs  4801 non-null   float64
 26  TTDspFA    4801 non-null   float64
 27  TTDspSS    4801 non-null   float64
 28  TTDspTwst  4801 non-null   int64
 29  PtfmSurge  4801 non-null   float64
 30  PtfmSway   4801 non-null   float64
 31  PtfmHeave  4801 non-null   float64
 32  PtfmRoll   4801 non-null   float64
 33  PtfmPitch  4801 non-null   float64
 34  PtfmYaw    4801 non-null   float64
 35  PtfmTAxt   4801 non-null   float64
 36  PtfmTAyt   4801 non-null   float64
 37  PtfmTAzt   4801 non-null   float64
 38  RootFxc1   4801 non-null   float64
 39  RootFyc1   4801 non-null   float64
 40  RootFzc1   4801 non-null   float64
 41  RootMxc1   4801 non-null   float64
 42  RootMyc1   4801 non-null   float64
 43  RootMzc1   4801 non-null   float64
 44  RootFxc2   4801 non-null   float64
 45  RootFyc2   4801 non-null   float64
 46  RootFzc2   4801 non-null   float64
 47  RootMxc2   4801 non-null   float64
 48  RootMyc2   4801 non-null   float64
 49  RootMzc2   4801 non-null   float64
 50  RootFxc3   4801 non-null   float64
 51  RootFyc3   4801 non-null   float64
 52  RootFzc3   4801 non-null   float64
 53  RootMxc3   4801 non-null   float64
 54  RootMyc3   4801 non-null   float64
 55  RootMzc3   4801 non-null   float64
 56  Spn1MLxb1  4801 non-null   float64
 57  Spn1MLyb1  4801 non-null   float64
 58  Spn1MLzb1  4801 non-null   float64
 59  Spn1MLxb2  4801 non-null   float64
 60  Spn1MLyb2  4801 non-null   float64
 61  Spn1MLzb2  4801 non-null   float64
 62  Spn1MLxb3  4801 non-null   float64
 63  Spn1MLyb3  4801 non-null   float64
 64  Spn1MLzb3  4801 non-null   float64
 65  RotThrust  4801 non-null   float64
 66  LSSGagFya  4801 non-null   float64
 67  LSSGagFza  4801 non-null   float64
 68  RotTorq    4801 non-null   float64
 69  LSSGagMya  4801 non-null   float64
 70  LSSGagMza  4801 non-null   float64
 71  YawBrFxp   4801 non-null   float64
 72  YawBrFyp   4801 non-null   float64
 73  YawBrFzp   4801 non-null   float64
 74  YawBrMxp   4801 non-null   float64
 75  YawBrMyp   4801 non-null   float64
 76  YawBrMzp   4801 non-null   float64
 77  TwrBsFxt   4801 non-null   float64
 78  TwrBsFyt   4801 non-null   float64
 79  TwrBsFzt   4801 non-null   float64
 80  TwrBsMxt   4801 non-null   float64
 81  TwrBsMyt   4801 non-null   float64
 82  TwrBsMzt   4801 non-null   float64
 83  TwHt1MLxt  4801 non-null   float64
 84  TwHt1MLyt  4801 non-null   float64
 85  TwHt1MLzt  4801 non-null   float64
 86  GenPwr     4801 non-null   float64
 87  GenTq      4801 non-null   float64
 88  Wave1Elev  4801 non-null   int64
 89  T[1]       4801 non-null   float64
 90  T[2]       4801 non-null   float64
 91  T[3]       4801 non-null   float64
 92  T[4]       4801 non-null   float64
 93  T[5]       4801 non-null   float64
 94  T[6]       4801 non-null   float64
 95  T[7]       4801 non-null   float64
 96  T[8]       4801 non-null   float64
dtypes: float64(92), int64(5)
memory usage: 3.6 MB

In [60]:
df1.describe()

,Time,Wind1VelX,Wind1VelY,Wind1VelZ,BldPitch1,BldPitch2,BldPitch3,Azimuth,RotSpeed,GenSpeed,...,GenTq,Wave1Elev,T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8]
count,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,...,24001.000000,24001.0,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000,24001.000000
mean,150.000000,16.982408,0.020335,0.007306,973.020237,973.020237,973.020237,140.733463,0.096728,9.415947,...,0.115767,0.0,257244.278296,266637.628135,283123.908004,296664.254247,296533.447076,282927.220164,266523.792192,257165.038237
std,86.607953,2.472728,1.983730,1.232373,142.859515,142.859515,142.859515,111.523473,2.065116,204.301296,...,30.587175,0.0,9424.151916,5341.758207,6973.809063,15742.486784,15235.583706,7116.199379,5878.479483,9363.166693
min,0.000000,10.282837,-5.308509,-4.364331,-4.756762,-4.756762,-4.756762,0.000000,-8.951620,-986.285583,...,-86.097481,0.0,236622.921875,251732.796875,269324.093750,273027.906250,273593.468750,273048.281250,252034.625000,239142.875000
25%,75.000000,15.159655,-1.370191,-0.825282,868.246277,868.246277,868.246277,48.437294,-1.335308,-128.456329,...,-22.722162,0.0,252473.109375,265237.968750,277524.812500,285134.468750,285892.281250,276981.968750,262863.500000,250466.968750
50%,150.000000,17.066320,-0.100139,0.009865,977.942627,977.942627,977.942627,115.702293,0.128932,8.199985,...,2.028628,0.0,258086.421875,266805.031250,281854.281250,295231.812500,291917.687500,281167.156250,266975.750000,258577.640625
75%,225.000000,18.780481,1.333478,0.849123,1075.935303,1075.935303,1075.935303,181.770615,1.407920,139.776794,...,24.716175,0.0,263492.406250,269035.843750,288568.125000,303436.531250,303261.437500,286671.531250,270530.062500,264520.812500
max,300.000000,25.013430,6.425784,4.628264,3229.204834,3229.204834,3229.204834,359.998779,9.937786,848.541565,...,47.402912,0.0,274366.812500,278617.281250,299085.593750,337340.375000,334850.125000,300052.000000,279715.968750,274470.500000

In [61]:
df2.describe()

,Time,Wind1VelX,Wind1VelY,Wind1VelZ,BldPitch1,BldPitch2,BldPitch3,Azimuth,RotSpeed,GenSpeed,...,GenTq,Wave1Elev,T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8]
count,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,...,4801.000000,4801.0,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000
mean,30.000000,12.935966,0.419425,-0.015828,741.176233,741.176233,741.176233,65.667841,0.104657,10.096347,...,7.378662,0.0,265524.596422,270184.525027,277919.607295,283767.801376,283850.539490,278044.607491,270320.523608,265561.285705
std,17.325921,1.164820,1.096784,1.105517,70.869591,70.869591,70.869591,120.428578,0.830666,81.199721,...,23.398929,0.0,6154.832768,3236.216411,3658.217766,7716.703408,8529.414273,2861.542711,2540.722227,6894.361620
min,0.000000,9.974622,-3.161915,-3.311421,0.000000,0.000000,0.000000,0.000000,-2.276885,-192.675949,...,-48.597206,0.0,254818.984375,265194.812500,273448.687500,273618.468750,273618.281250,273740.687500,264583.968750,253472.312500
25%,15.000000,12.122225,-0.339005,-0.812086,694.741455,694.741455,694.741455,9.740669,-0.460206,-42.378468,...,-10.909654,0.0,260847.468750,267064.468750,274298.968750,276614.718750,275481.218750,275471.437500,268398.312500,258340.437500
50%,30.000000,12.857203,0.544393,-0.028077,736.791565,736.791565,736.791565,15.924121,0.072565,5.292792,...,5.402868,0.0,265422.562500,270684.156250,276527.031250,282089.437500,282579.531250,277880.343750,270317.093750,267150.562500
75%,45.000000,13.705134,1.219170,0.756328,785.206970,785.206970,785.206970,29.594635,0.757011,71.647995,...,26.590336,0.0,271638.375000,273416.687500,281829.375000,290618.562500,291231.375000,279946.562500,272637.718750,272306.625000
max,60.000000,16.446257,3.123255,3.395926,1997.871948,1997.871948,1997.871948,359.999908,2.300402,238.801056,...,47.402912,0.0,274366.812500,274470.500000,284604.375000,299745.093750,298022.531250,283886.343750,274366.812500,274470.500000