# Import Libraries

In [2]:
import pandas as pd
import os

# File's Path

In [3]:
notebook_path = os.getcwd()
db_files_path = "D:\Documentos\Turbinas\Test_22ITIBarge5MWSimulations"

In [7]:
#print(notebook_path)
#print(db_files_path)

C:\Users\Victor Ramos Fuentes\Documents\Turbinas
D:\Documentos\Turbinas\Test_22ITIBarge5MWSimulations

In [4]:
fileN0 = db_files_path + "\Test22pulsetrendWindpitch0.xlsx"
fileN20 = db_files_path + "\Test22pulsetrendWindpitch20.xlsx"
fileN40 = db_files_path + "\Test22pulsetrendWindpitch40.xlsx"
fileN60 = db_files_path + "\Test22pulsetrendWindpitch60.xlsx"
fileN80 = db_files_path + "\Test22pulsetrendWindpitch80.xlsx"

# Read File

In [5]:
df1 = pd.read_excel(fileN0)
df2 = pd.read_excel(fileN20)
df3 = pd.read_excel(fileN40)
df4 = pd.read_excel(fileN60)
df5 = pd.read_excel(fileN80)

# File's Analysis

## File's dimensions

In [6]:
print("File J1 -> " + "Number of rows: " + str(df1.shape[0]) + " Number of columns: " + str(df1.shape[1]))
print("File J2 -> " + "Number of rows: " + str(df2.shape[0]) + " Number of columns: " + str(df2.shape[1]))
print("File J3 -> " + "Number of rows: " + str(df3.shape[0]) + " Number of columns: " + str(df3.shape[1]))
print("File J4 -> " + "Number of rows: " + str(df4.shape[0]) + " Number of columns: " + str(df4.shape[1]))
print("File J5 -> " + "Number of rows: " + str(df5.shape[0]) + " Number of columns: " + str(df5.shape[1]))

File J1 -> Number of rows: 72001 Number of columns: 97
File J2 -> Number of rows: 72001 Number of columns: 97
File J3 -> Number of rows: 72001 Number of columns: 97
File J4 -> Number of rows: 72001 Number of columns: 97
File J5 -> Number of rows: 72001 Number of columns: 97

## File's columns

In [7]:
df1.columns

Index(['Time', 'Wind1VelX', 'Wind1VelY', 'Wind1VelZ', 'BldPitch1', 'BldPitch2',
       'BldPitch3', 'Azimuth', 'RotSpeed', 'GenSpeed', 'NacYaw', 'OoPDefl1',
       'IPDefl1', 'TwstDefl1', 'OoPDefl2', 'IPDefl2', 'TwstDefl2', 'OoPDefl3',
       'IPDefl3', 'TwstDefl3', 'TwrClrnc1', 'TwrClrnc2', 'TwrClrnc3',
       'NcIMUTAxs', 'NcIMUTAys', 'NcIMUTAzs', 'TTDspFA', 'TTDspSS',
       'TTDspTwst', 'PtfmSurge', 'PtfmSway', 'PtfmHeave', 'PtfmRoll',
       'PtfmPitch', 'PtfmYaw', 'PtfmTAxt', 'PtfmTAyt', 'PtfmTAzt', 'RootFxc1',
       'RootFyc1', 'RootFzc1', 'RootMxc1', 'RootMyc1', 'RootMzc1', 'RootFxc2',
       'RootFyc2', 'RootFzc2', 'RootMxc2', 'RootMyc2', 'RootMzc2', 'RootFxc3',
       'RootFyc3', 'RootFzc3', 'RootMxc3', 'RootMyc3', 'RootMzc3', 'Spn1MLxb1',
       'Spn1MLyb1', 'Spn1MLzb1', 'Spn1MLxb2', 'Spn1MLyb2', 'Spn1MLzb2',
       'Spn1MLxb3', 'Spn1MLyb3', 'Spn1MLzb3', 'RotThrust', 'LSSGagFya',
       'LSSGagFza', 'RotTorq', 'LSSGagMya', 'LSSGagMza', 'YawBrFxp',
       'YawBrFyp', 'YawBrFzp', 'YawBrMxp', 'YawBrMyp', 'YawBrMzp', 'TwrBsFxt',
       'TwrBsFyt', 'TwrBsFzt', 'TwrBsMxt', 'TwrBsMyt', 'TwrBsMzt', 'TwHt1MLxt',
       'TwHt1MLyt', 'TwHt1MLzt', 'GenPwr', 'GenTq', 'Wave1Elev', 'T[1]',
       'T[2]', 'T[3]', 'T[4]', 'T[5]', 'T[6]', 'T[7]', 'T[8]'],
      dtype='object')

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72001 entries, 0 to 72000
Data columns (total 97 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Time       72001 non-null  float64
 1   Wind1VelX  72001 non-null  float64
 2   Wind1VelY  72001 non-null  int64
 3   Wind1VelZ  72001 non-null  int64
 4   BldPitch1  72001 non-null  int64
 5   BldPitch2  72001 non-null  int64
 6   BldPitch3  72001 non-null  int64
 7   Azimuth    72001 non-null  float64
 8   RotSpeed   72001 non-null  float64
 9   GenSpeed   72001 non-null  float64
 10  NacYaw     72001 non-null  float64
 11  OoPDefl1   72001 non-null  float64
 12  IPDefl1    72001 non-null  float64
 13  TwstDefl1  72001 non-null  int64
 14  OoPDefl2   72001 non-null  float64
 15  IPDefl2    72001 non-null  float64
 16  TwstDefl2  72001 non-null  int64
 17  OoPDefl3   72001 non-null  float64
 18  IPDefl3    72001 non-null  float64
 19  TwstDefl3  72001 non-null  int64
 20  TwrClrnc1  72001 non-null  float64
 21  TwrClrnc2  72001 non-null  float64
 22  TwrClrnc3  72001 non-null  float64
 23  NcIMUTAxs  72001 non-null  float64
 24  NcIMUTAys  72001 non-null  float64
 25  NcIMUTAzs  72001 non-null  float64
 26  TTDspFA    72001 non-null  float64
 27  TTDspSS    72001 non-null  float64
 28  TTDspTwst  72001 non-null  int64
 29  PtfmSurge  72001 non-null  float64
 30  PtfmSway   72001 non-null  float64
 31  PtfmHeave  72001 non-null  float64
 32  PtfmRoll   72001 non-null  float64
 33  PtfmPitch  72001 non-null  float64
 34  PtfmYaw    72001 non-null  float64
 35  PtfmTAxt   72001 non-null  float64
 36  PtfmTAyt   72001 non-null  float64
 37  PtfmTAzt   72001 non-null  float64
 38  RootFxc1   72001 non-null  float64
 39  RootFyc1   72001 non-null  float64
 40  RootFzc1   72001 non-null  float64
 41  RootMxc1   72001 non-null  float64
 42  RootMyc1   72001 non-null  float64
 43  RootMzc1   72001 non-null  float64
 44  RootFxc2   72001 non-null  float64
 45  RootFyc2   72001 non-null  float64
 46  RootFzc2   72001 non-null  float64
 47  RootMxc2   72001 non-null  float64
 48  RootMyc2   72001 non-null  float64
 49  RootMzc2   72001 non-null  float64
 50  RootFxc3   72001 non-null  float64
 51  RootFyc3   72001 non-null  float64
 52  RootFzc3   72001 non-null  float64
 53  RootMxc3   72001 non-null  float64
 54  RootMyc3   72001 non-null  float64
 55  RootMzc3   72001 non-null  float64
 56  Spn1MLxb1  72001 non-null  float64
 57  Spn1MLyb1  72001 non-null  float64
 58  Spn1MLzb1  72001 non-null  float64
 59  Spn1MLxb2  72001 non-null  float64
 60  Spn1MLyb2  72001 non-null  float64
 61  Spn1MLzb2  72001 non-null  float64
 62  Spn1MLxb3  72001 non-null  float64
 63  Spn1MLyb3  72001 non-null  float64
 64  Spn1MLzb3  72001 non-null  float64
 65  RotThrust  72001 non-null  float64
 66  LSSGagFya  72001 non-null  float64
 67  LSSGagFza  72001 non-null  float64
 68  RotTorq    72001 non-null  float64
 69  LSSGagMya  72001 non-null  float64
 70  LSSGagMza  72001 non-null  float64
 71  YawBrFxp   72001 non-null  float64
 72  YawBrFyp   72001 non-null  float64
 73  YawBrFzp   72001 non-null  float64
 74  YawBrMxp   72001 non-null  float64
 75  YawBrMyp   72001 non-null  float64
 76  YawBrMzp   72001 non-null  float64
 77  TwrBsFxt   72001 non-null  float64
 78  TwrBsFyt   72001 non-null  float64
 79  TwrBsFzt   72001 non-null  float64
 80  TwrBsMxt   72001 non-null  float64
 81  TwrBsMyt   72001 non-null  float64
 82  TwrBsMzt   72001 non-null  float64
 83  TwHt1MLxt  72001 non-null  float64
 84  TwHt1MLyt  72001 non-null  float64
 85  TwHt1MLzt  72001 non-null  float64
 86  GenPwr     72001 non-null  float64
 87  GenTq      72001 non-null  float64
 88  Wave1Elev  72001 non-null  int64
 89  T[1]       72001 non-null  float64
 90  T[2]       72001 non-null  float64
 91  T[3]       72001 non-null  float64
 92  T[4]       72001 non-null  float64
 93  T[5]       72001 non-null  float64
 94  T[6]       72001 non-null  float64
 95  T[7]       72001 non-null  float64
 96  T[8]       72001 non-null  float64
dtypes: float64(87), int64(10)
memory usage: 53.3 MB

In [9]:
df1.describe()

,Time,Wind1VelX,Wind1VelY,Wind1VelZ,BldPitch1,BldPitch2,BldPitch3,Azimuth,RotSpeed,GenSpeed,...,GenTq,Wave1Elev,T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8]
count,72001.000000,72001.000000,72001.0,72001.0,72001.0,72001.0,72001.0,72001.000000,72001.000000,72001.000000,...,72001.000000,72001.0,72001.000000,72001.000000,72001.000000,7.200100e+04,7.200100e+04,72001.000000,72001.000000,72001.000000
mean,450.000000,9.822364,0.0,0.0,0.0,0.0,0.0,153.256005,15.028449,1457.758233,...,15.829548,0.0,225525.055834,247248.509375,341084.679769,6.377715e+05,6.205601e+05,339253.373170,246955.956968,225267.170721
std,259.813034,5.950616,0.0,0.0,0.0,0.0,0.0,110.615799,15.080984,1462.859484,...,14.076231,0.0,35451.486326,20631.693272,64954.290102,4.700337e+05,4.292704e+05,62750.551195,20944.744601,35577.018074
min,0.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.000000,-0.003020,-0.365780,...,0.000000,0.0,182056.093750,217262.765625,273424.937500,2.735611e+05,2.734576e+05,273527.625000,214863.859375,181483.078125
25%,225.000000,5.000000,0.0,0.0,0.0,0.0,0.0,49.946602,0.934534,90.649750,...,0.000000,0.0,193366.640625,227457.968750,274788.062500,2.760678e+05,2.760256e+05,274819.093750,230579.296875,193557.234375
50%,450.000000,10.000000,0.0,0.0,0.0,0.0,0.0,143.723434,11.030831,1069.991089,...,13.909478,0.0,213089.390625,242959.968750,330951.562500,4.479246e+05,4.476967e+05,326735.562500,242055.156250,212249.000000
75%,675.000000,13.000000,0.0,0.0,0.0,0.0,0.0,248.134369,23.441172,2273.786133,...,27.769957,0.0,271845.281250,273091.156250,383251.312500,7.690169e+05,7.906814e+05,391048.843750,273046.218750,271879.343750
max,900.000000,20.000000,0.0,0.0,0.0,0.0,0.0,359.999969,46.368286,4497.955078,...,43.528408,0.0,274366.812500,274470.500000,478360.781250,1.965048e+06,1.809010e+06,461623.687500,274366.812500,274470.500000

In [10]:
df2.describe()

,Time,Wind1VelX,Wind1VelY,Wind1VelZ,BldPitch1,BldPitch2,BldPitch3,Azimuth,RotSpeed,GenSpeed,...,GenTq,Wave1Elev,T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8]
count,72001.000000,72001.000000,72001.0,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,...,72001.000000,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000
mean,450.000000,9.822364,0.0,0.0,19.999998,19.999998,19.999998,174.736056,0.378050,36.668325,...,12.475227,0.0,261285.350057,269082.970853,281354.138233,291935.014489,290479.120686,280049.156113,267373.039895,261025.656962
std,259.813034,5.950616,0.0,0.0,0.182574,0.182574,0.182574,105.489475,1.156859,111.122953,...,28.276711,0.0,11144.997675,4512.000092,7492.059982,18438.110653,16945.544384,5912.615690,5959.185552,11476.829232
min,0.000000,1.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,-2.047304,-198.056564,...,-61.159660,0.0,234423.015625,258182.781250,271444.250000,268773.593750,268741.875000,271489.500000,252016.062500,233278.125000
25%,225.000000,5.000000,0.0,0.0,19.999998,19.999998,19.999998,82.869614,-0.632836,-60.035202,...,-9.784583,0.0,256169.968750,266768.437500,276048.687500,278772.062500,278774.906250,275679.437500,264615.750000,255679.140625
50%,450.000000,10.000000,0.0,0.0,19.999998,19.999998,19.999998,172.352539,0.304282,29.659269,...,15.340341,0.0,262590.125000,269632.468750,279649.687500,287399.468750,286552.062500,278886.625000,268421.750000,262387.218750
75%,675.000000,13.000000,0.0,0.0,19.999998,19.999998,19.999998,266.617126,1.382159,132.842819,...,39.339859,0.0,269166.656250,272515.093750,283828.843750,296709.312500,295290.718750,282420.125000,271638.500000,269555.375000
max,900.000000,20.000000,0.0,0.0,60.000000,60.000000,60.000000,359.999969,2.986382,289.029083,...,47.402912,0.0,279388.406250,276477.125000,302964.468750,346879.156250,340406.218750,296097.968750,276266.437500,279564.781250

In [11]:
df3.describe()

,Time,Wind1VelX,Wind1VelY,Wind1VelZ,BldPitch1,BldPitch2,BldPitch3,Azimuth,RotSpeed,GenSpeed,...,GenTq,Wave1Elev,T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8]
count,72001.000000,72001.000000,72001.0,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,...,72001.000000,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000
mean,450.000000,9.822364,0.0,0.0,39.999996,39.999996,39.999996,195.798391,0.199780,19.372960,...,16.844704,0.0,265318.636161,271016.482795,278561.577346,285305.379251,283803.164580,277845.403655,269372.220706,265357.800945
std,259.813034,5.950616,0.0,0.0,0.365148,0.365148,0.365148,111.074895,0.882648,84.616933,...,26.163042,0.0,8134.225828,2733.503345,5674.177682,12358.337866,10443.600424,3499.745388,5042.388565,8712.990559
min,0.000000,1.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,-1.836462,-177.057419,...,-57.409714,0.0,244651.625000,264403.468750,271135.750000,270258.843750,270245.718750,272163.156250,255630.031250,243147.437500
25%,225.000000,5.000000,0.0,0.0,39.999996,39.999996,39.999996,106.745697,-0.505229,-47.632721,...,-3.971968,0.0,261323.921875,269188.562500,274245.625000,275872.531250,275720.500000,274898.437500,267122.562500,261146.843750
50%,450.000000,10.000000,0.0,0.0,39.999996,39.999996,39.999996,184.645035,0.069930,9.461185,...,20.777782,0.0,266269.062500,270907.187500,276953.250000,282364.843750,281689.437500,277782.468750,270558.062500,266805.250000
75%,675.000000,13.000000,0.0,0.0,39.999996,39.999996,39.999996,297.522217,0.964059,92.464546,...,42.151440,0.0,271913.562500,273412.812500,280515.593750,289366.656250,287639.312500,279764.937500,273438.468750,272364.281250
max,900.000000,20.000000,0.0,0.0,120.000000,120.000000,120.000000,359.999969,2.197978,212.078430,...,47.402912,0.0,277730.718750,275733.656250,294975.906250,322836.750000,313981.375000,287259.593750,276576.281250,277775.968750

In [12]:
df4.describe()

,Time,Wind1VelX,Wind1VelY,Wind1VelZ,BldPitch1,BldPitch2,BldPitch3,Azimuth,RotSpeed,GenSpeed,...,GenTq,Wave1Elev,T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8]
count,72001.000000,72001.000000,72001.0,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,...,72001.000000,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000
mean,450.000000,9.822364,0.0,0.0,60.000000,60.000000,60.000000,153.600626,0.283818,27.524922,...,18.220107,0.0,270778.256922,274063.847185,276675.275201,278765.642357,276843.488418,274368.930983,270914.940931,270090.660516
std,259.813034,5.950616,0.0,0.0,0.547723,0.547723,0.547723,116.490007,0.824706,79.158845,...,25.746601,0.0,3686.519936,701.094738,3427.722597,5639.527555,3726.471158,807.719628,3400.109134,4604.786420
min,0.000000,1.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,-1.470504,-141.587051,...,-48.375057,0.0,261626.078125,272172.781250,271634.875000,269945.687500,269773.250000,271769.062500,261236.078125,257884.843750
25%,225.000000,5.000000,0.0,0.0,60.000000,60.000000,60.000000,42.928883,-0.383374,-36.082424,...,-2.472323,0.0,268647.250000,273596.656250,274122.062500,274336.062500,274043.906250,273959.187500,269389.500000,267606.187500
50%,450.000000,10.000000,0.0,0.0,60.000000,60.000000,60.000000,132.926697,0.213266,20.029331,...,22.653036,0.0,271084.968750,273927.562500,275949.781250,277759.031250,276413.218750,274564.500000,271481.531250,270720.406250
75%,675.000000,13.000000,0.0,0.0,60.000000,60.000000,60.000000,240.644272,0.983904,94.136017,...,44.403645,0.0,273635.875000,274431.312500,277995.843750,281408.468750,278896.343750,274922.531250,273576.531250,273755.875000
max,900.000000,20.000000,0.0,0.0,180.000000,180.000000,180.000000,359.999969,1.633384,158.450684,...,47.402912,0.0,278019.750000,276444.593750,287091.843750,294985.687500,286659.625000,275812.843750,276345.125000,278098.625000

In [13]:
df5.describe()

,Time,Wind1VelX,Wind1VelY,Wind1VelZ,BldPitch1,BldPitch2,BldPitch3,Azimuth,RotSpeed,GenSpeed,...,GenTq,Wave1Elev,T[1],T[2],T[3],T[4],T[5],T[6],T[7],T[8]
count,72001.000000,72001.000000,72001.0,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,...,72001.000000,72001.0,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000,72001.000000
mean,450.000000,9.822364,0.0,0.0,79.999992,79.999992,79.999992,69.065568,0.011041,1.067055,...,11.492561,0.0,273675.242580,274602.936744,274718.205356,274901.754647,273983.713639,273509.349903,272953.577925,273245.223202
std,259.813034,5.950616,0.0,0.0,0.730297,0.730297,0.730297,95.048315,0.561947,53.585639,...,21.575365,0.0,1377.421662,551.172528,1409.689051,2028.702217,1301.509337,494.268712,1477.134900,1875.937611
min,0.000000,1.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,-1.253085,-120.792496,...,-42.000126,0.0,271040.843750,273008.125000,272044.468750,270131.281250,270132.656250,272113.406250,269248.906250,268975.687500
25%,225.000000,5.000000,0.0,0.0,79.999992,79.999992,79.999992,25.724922,-0.311067,-28.889168,...,-4.314255,0.0,272714.281250,274208.093750,273764.000000,273601.750000,273302.875000,273236.093750,272334.562500,272027.000000
50%,450.000000,10.000000,0.0,0.0,79.999992,79.999992,79.999992,46.520306,-0.000631,-0.040220,...,14.062438,0.0,273628.812500,274581.625000,274478.281250,274805.250000,274047.218750,273525.093750,273198.281250,273316.156250
75%,675.000000,13.000000,0.0,0.0,79.999992,79.999992,79.999992,58.146847,0.335807,31.280693,...,29.812078,0.0,274410.812500,274966.343750,275337.562500,276123.187500,274886.562500,273865.468750,273974.781250,274426.156250
max,900.000000,20.000000,0.0,0.0,240.000000,240.000000,240.000000,359.999969,1.321708,127.597603,...,47.402912,0.0,277755.468750,275928.812500,278336.062500,279652.468750,276540.343750,274950.406250,275891.968750,277859.031250